### PR TITLE
Fix Applicative-Monad for GHC 7.10.1

### PR DESCRIPTION
**Pull request by ony**

### CODE REVIEW

**Comment by magthe** [comment]
I'm just curious, are you using this? And for what?

**Comment by ony** [comment]
@magthe I tried it to bring some haskell packages into ArchLinux at home. Then I saw that [cblrepo](/magthe/cblrepo).
But at the end given up and switched to cabal-install in sandbox :)

**Comment by magthe** [comment]
I hope you've seen [ArchHaskell](https://wiki.archlinux.org/index.php/ArchHaskell) and the accompanying repo at https://github.com/archhaskell/habs/.

What packages was it you were interested in?

**Comment by ony** [comment]
@magthe I was interested in `yesod` with its family and `ParserFunction`. But most of packages on AUR are GHC-7.8.3.

Thank you for pointing to that [ArchHaskell](https://wiki.archlinux.org/index.php/ArchHaskell). I didn't looked into it that time. But looks like `yesod` only available at AUR.

**Comment by LeifW** [comment]
This could use a version bump and an upload to hackage. I could submit a PR for the version bump and upload it to hackage myself? The current release on hackage doesn't build on GHC 7.10. Also, there's a few other outstanding PR's opened against this repo.

**Comment by ony** [comment]
@LeifW as I understand this stuff is outdated and [cblrepo](https://github.com/magthe/cblrepo) is extended version of this.

**Comment by magthe** [comment]
@LeifW I'm not sure if the two ancient projects, `archlinux` and `cabal2arch`, have any raison d'etre nowadays.  If they do, please feel free to work on them.

**Pull request merged**
